# Generated by Django 4.2.5 on 2023-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('stock_price', models.FloatField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('operating_expense', models.FloatField(blank=True, null=True)),
                ('net_income', models.FloatField(blank=True, null=True)),
                ('net_profit_margin', models.FloatField(blank=True, null=True)),
                ('earnings_per_share', models.FloatField(blank=True, null=True)),
                ('ebitda', models.FloatField(blank=True, null=True)),
                ('effective_tax_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Data',
                'verbose_name_plural': 'Stock Data',
            },
        ),
    ]
