# Generated by Django 4.2.5 on 2023-09-23 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
